### ISSUE TITLE
Make Yieldgate available on other testnet chains

### ISSUE THREAD

**Issue by sebastianst** [yieldgate/yieldgate#2]
* The frontend currently has the Polygon Mumbai chain hardcoded, including the native token unit `MATIC`.
* The hardhat deploy script also has Mumbai hardcoded, including the chain id, Aave contract addresses (`WETHGateway`, `Pool` and native `aToken`).

It should be easy to make other testnets available.
* The frontend could query the chain id from the web3 provider and then read the relevant information from a static list. @wottpal feel free to expand on this.
* Similarly, for the hardhat deploy script, we can define a list of static data and then pass the chain(s) to deploy to via cmdline flags. I'd do that.

**Comment by wottpal** [comment]
i'll work on the frontend/database part of this in `feature/dz-2`.

**Comment by raulrpearson** [comment]
Hey, this issue seems  like it possibly was already solved. You've probably seen the email about the [merge affecting testnets](https://www.alchemy.com/the-merge): we should stop using/referencing Rinkeby and Koven and just use Goerli as a testnet, right?

**Comment by sebastianst** [comment]
Yes we should ditch Rinkeby. We still need to deploy to Goerli though. IIRC Aave wasn't deployed on Goerli 2 months ago, which is why we deployed to Rinkeby. Tracked in #34 so closing this one.
