### ISSUE TITLE
Improve frontend build pipeline to generate contract artifacts

### ISSUE THREAD

**Issue by sebastianst** [yieldgate/yieldgate#4]
Currently, the folders `packages/frontend/artifacts/contracts/` and `packages/frontend/types/typechain/` are kept in git. These files are generated from the contracts with `npx hardhat compile` from the `hardhat` workspace package. Because of this, every time the contract is changed, all these files need to be updated in git. And merge conflicts can arise if different people change the contracts.

So I propose that
1. these files are removed from git and ignored and
2. the frontend build pipeline should generate them

**Comment by wottpal** [comment]
resolved in https://github.com/yieldgate/yieldgate/commit/cb6dc41817a305cd7c995aad27d8f2b329bfddc9
