### ISSUE TITLE
Contracts: Remove implicit deployment of sponsor pools

### ISSUE THREAD

**Issue by sebastianst** [yieldgate/yieldgate#41]
Currently, the first sponsor to stake for any beneficiary implicitly deploys the sponsor pool. This made sense in the context of the hackathon, but is not good practice. So we make pool deployments explicit. Open question whether to have an explicit `deployAndStake` function that does both. Might get complicated once we change the public interface so that pool interactions are directly with the pool contracts instead of forwarding functions on the main contract.

This needs follow-up changes in the frontend. When loading a profile page, it has to be checked whether there's already a pool deployed. It can then show the option "Deploy" and maybe a second option "Deploy & Stake".

**Comment by wottpal** [comment]
The "deploy & stake" would only be useful if someone is deploying for someone else on their behalf, right? I just thought this will be mainly us, to onboard some public-goods/creators with a big audience to bootstrap usage of the platform. Or would we allow anyone to open profiles on anyones behalf? 

If I'm deploying a profile just for myself it's probably a rare case, that I also want to stake in the same step. (I mean I can just use AAVE or other platforms to generate yield for myself).

From a technical point of view, what would be pros/cons to just having a single, payable `deploy` function that stakes implicitly whether a value (ETH/MATIC) is sent or not.

**Comment by sebastianst** [comment]
Yes, deploy+stake is for deploying a pool for someone else and then staking at the same time, saving tx cost. But it's probalby a premature optimization if it is not trivial to implement.

**Comment by sebastianst** [comment]
The payable deploy function would work for native token staking, yes, but I would find it semantically confusing. Better have an explicit function `deployAndStake` that just calls `deploy` and then `stake` one after another. And for token staking it wouldn't work.

**Comment by wottpal** [comment]
> Yes, deploy+stake is for deploying a pool for someone else and then staking at the same time, saving tx cost. But it's probalby a premature optimization if it is not trivial to implement.

I tend to agree. We should therefore maybe remove the `deployAndStake` from the scope right now and only focus this issue on the deployment<->staking separation.
